### PR TITLE
upgrade to Swift 3 and Xcode 8

### PR DESCRIPTION
**Pull request by joshuatbrown**

### CODE REVIEW

**Comment by macteo** [comment]
Hi Josh, thanks for your contribution, much appreciated. 

Could you please try to edit the *.travis.yml* file replacing line 2 with
```yaml
osx_image: xcode8.1
```

so the build will run on that image and it can check for errors?

As soon as the change is made and tests are passing I'll accept the pull request.
Thanks again for your help.

**Comment by joshuatbrown** [comment]
@macteo Updated. Looks like everything passed.

**Comment by macteo** [comment]
Thank you very much!

**Comment by joshuatbrown** [comment]
@macteo you're welcome! I'd love to point our Podfile to a new version of SabBar with the Swift 3 changes here; are you planning a new release?

**Comment by macteo** [comment]
I'll definitely do it during the afternoon.

**Comment by macteo** [comment]
Version [1.0.0](https://cocoapods.org/pods/SabBar) up and running.

**Pull request merged**
